<template><div><h1 id="api" tabindex="-1"><a class="header-anchor" href="#api"><span>API</span></a></h1>
<h2 id="session" tabindex="-1"><a class="header-anchor" href="#session"><span>Session</span></a></h2>
<h3 id="开始会话" tabindex="-1"><a class="header-anchor" href="#开始会话"><span>开始会话</span></a></h3>
<h4 id="post-session-complete" tabindex="-1"><a class="header-anchor" href="#post-session-complete"><span>POST <code v-pre>/session/complete</code></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line"></span>
<span class="line">export interface Request {</span>
<span class="line">    intent?: Intent;</span>
<span class="line">    messages: Message[];</span>
<span class="line">    session_id: string;</span>
<span class="line">    team_id: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Intent {</span>
<span class="line">    category: string;</span>
<span class="line">    content: string;</span>
<span class="line">    intent_id: string;</span>
<span class="line">    tag: string;</span>
<span class="line">    title: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Message {</span>
<span class="line">    content?: string;</span>
<span class="line">    role?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查看进行中的会话" tabindex="-1"><a class="header-anchor" href="#查看进行中的会话"><span>查看进行中的会话</span></a></h3>
<h4 id="get-session-current" tabindex="-1"><a class="header-anchor" href="#get-session-current"><span>GET <code v-pre>/session/current</code></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">export interface Response {</span>
<span class="line">    code: number;</span>
<span class="line">    data: Datum[];</span>
<span class="line">    msg: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Datum {</span>
<span class="line">    browser_id?: string;</span>
<span class="line">    created_at?: string;</span>
<span class="line">    duration?: number;</span>
<span class="line">    error_message?: string;</span>
<span class="line">    messages?: Message[];</span>
<span class="line">    session_id?: string;</span>
<span class="line">    status?: string;</span>
<span class="line">    task?: Task[];</span>
<span class="line">    task_result?: TaskResult;</span>
<span class="line">    team_id?: string;</span>
<span class="line">    tokens?: Tokens;</span>
<span class="line">    updated_at?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Message {</span>
<span class="line">    content?: string;</span>
<span class="line">    created_at?: string;</span>
<span class="line">    message_id?: string;</span>
<span class="line">    message_type?: string;</span>
<span class="line">    source?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Task {</span>
<span class="line">    content?: string;</span>
<span class="line">    role?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface TaskResult {</span>
<span class="line">    content: string;</span>
<span class="line">    source: string;</span>
<span class="line">    type: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Tokens {</span>
<span class="line">    models: Models;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Models {</span>
<span class="line">    "58612030-0189-42a2-9ad9-1ae5ac64002d": The58612030018942A29Ad91Ae5Ac64002D;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface The58612030018942A29Ad91Ae5Ac64002D {</span>
<span class="line">    completion_tokens: number;</span>
<span class="line">    prompt_tokens: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查看-session-详情" tabindex="-1"><a class="header-anchor" href="#查看-session-详情"><span>查看 session 详情</span></a></h3>
<h4 id="get-session-info-session-id" tabindex="-1"><a class="header-anchor" href="#get-session-info-session-id"><span>GET <code v-pre>/session/info/{session_id}</code></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">export interface Request {</span>
<span class="line">    session_id: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface RequestHeaders {</span>
<span class="line">    Authorization?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Response {</span>
<span class="line">    code: number;</span>
<span class="line">    data: Data;</span>
<span class="line">    msg: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Data {</span>
<span class="line">    browser_id: string;</span>
<span class="line">    created_at: string;</span>
<span class="line">    duration: number;</span>
<span class="line">    error_message: string;</span>
<span class="line">    messages: Message[];</span>
<span class="line">    name: string;</span>
<span class="line">    platform: string;</span>
<span class="line">    session_id: string;</span>
<span class="line">    status: string;</span>
<span class="line">    task: Task[];</span>
<span class="line">    task_result: TaskResult;</span>
<span class="line">    team_id: string;</span>
<span class="line">    tokens: Tokens;</span>
<span class="line">    updated_at: string;</span>
<span class="line">    visibility: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Message {</span>
<span class="line">    content: string;</span>
<span class="line">    created_at: string;</span>
<span class="line">    message_id: string;</span>
<span class="line">    message_type: string;</span>
<span class="line">    source: string;</span>
<span class="line">    source_type: string;</span>
<span class="line">    type: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Task {</span>
<span class="line">    content?: string;</span>
<span class="line">    role?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface TaskResult {</span>
<span class="line">    content: string;</span>
<span class="line">    source: string;</span>
<span class="line">    type: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Tokens {</span>
<span class="line">    models: { [key: string]: any };</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查看-browser-详情" tabindex="-1"><a class="header-anchor" href="#查看-browser-详情"><span>查看 browser 详情</span></a></h3>
<h4 id="get-browser-info-browser-id" tabindex="-1"><a class="header-anchor" href="#get-browser-info-browser-id"><span>GET <code v-pre>/browser/info/{browser_id}</code></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">export interface Request {</span>
<span class="line">    browser_id: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface RequestHeaders {</span>
<span class="line">    Authorization?: string;</span>
<span class="line">    "x-api-key"?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Response {</span>
<span class="line">    code: number;</span>
<span class="line">    data: Data;</span>
<span class="line">    msg: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Data {</span>
<span class="line">    browser_id: string;</span>
<span class="line">    created_at: string;</span>
<span class="line">    duration_seconds: number;</span>
<span class="line">    height: number;</span>
<span class="line">    session_id: string;</span>
<span class="line">    solve_captcha: boolean;</span>
<span class="line">    status: string;</span>
<span class="line">    timezone: string;</span>
<span class="line">    user_agent: string;</span>
<span class="line">    user_id: string;</span>
<span class="line">    width: number;</span>
<span class="line">    ws_endpoint: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查看-message-记录" tabindex="-1"><a class="header-anchor" href="#查看-message-记录"><span>查看 message 记录</span></a></h3>
<h4 id="get-session-message-lists" tabindex="-1"><a class="header-anchor" href="#get-session-message-lists"><span>GET <code v-pre>/session/message/lists</code></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line"></span>
<span class="line">export interface Request {</span>
<span class="line">    page_num?: number;</span>
<span class="line">    page_size?: number;</span>
<span class="line">    session_id?: string;</span>
<span class="line">    sort_order?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface RequestHeaders {</span>
<span class="line">    Authorization?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Response {</span>
<span class="line">    code: number;</span>
<span class="line">    data: Datum[];</span>
<span class="line">    msg: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Datum {</span>
<span class="line">    content: string;</span>
<span class="line">    created_at: string;</span>
<span class="line">    message_id: string;</span>
<span class="line">    message_type: string;</span>
<span class="line">    source: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查看-plan-计划" tabindex="-1"><a class="header-anchor" href="#查看-plan-计划"><span>查看 plan 计划</span></a></h3>
<h4 id="get-plan-lists-session-id-deprecated" tabindex="-1"><a class="header-anchor" href="#get-plan-lists-session-id-deprecated"><span><s>GET <code v-pre>/plan/lists/{session_id}</code> (deprecated)</s></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">export interface Request {</span>
<span class="line">    session_id: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface RequestQueryParmas {</span>
<span class="line">    page_num?: number;</span>
<span class="line">    page_size?: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface RequestHeaders {</span>
<span class="line">    Authorization?: string;</span>
<span class="line">}</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="agents" tabindex="-1"><a class="header-anchor" href="#agents"><span>Agents</span></a></h2>
<h3 id="查看-agent-列表" tabindex="-1"><a class="header-anchor" href="#查看-agent-列表"><span>查看 agent 列表</span></a></h3>
<h4 id="get-agent-lists" tabindex="-1"><a class="header-anchor" href="#get-agent-lists"><span>GET <code v-pre>/agent/lists</code></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">export interface Request {</span>
<span class="line">    page_num?: number;</span>
<span class="line">    page_size?: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface RequestHeaders {</span>
<span class="line">    Authorization?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Response {</span>
<span class="line">    code: number;</span>
<span class="line">    data: Data;</span>
<span class="line">    msg: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Data {</span>
<span class="line">    data: Datum[];</span>
<span class="line">    page_num: number;</span>
<span class="line">    page_size: number;</span>
<span class="line">    total: number;</span>
<span class="line">    total_page: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Datum {</span>
<span class="line">    agent_id: string;</span>
<span class="line">    agent_type: string;</span>
<span class="line">    avatar: string;</span>
<span class="line">    component_type: string;</span>
<span class="line">    created_at: string;</span>
<span class="line">    description: string;</span>
<span class="line">    model: Model;</span>
<span class="line">    name: string;</span>
<span class="line">    parameters: Parameters;</span>
<span class="line">    system_message: string;</span>
<span class="line">    updated_at: string;</span>
<span class="line">    user_id: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Model {</span>
<span class="line">    created_at: string;</span>
<span class="line">    icon_url: string;</span>
<span class="line">    model_type: string;</span>
<span class="line">    provider: string;</span>
<span class="line">    system_model_id: string;</span>
<span class="line">    updated_at: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Parameters {</span>
<span class="line">    system_prompt_role: string;</span>
<span class="line">    system_prompt_task_skill: string;</span>
<span class="line">    temperature: Temperature;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export type Temperature = number | number;</span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查看-agent-详情" tabindex="-1"><a class="header-anchor" href="#查看-agent-详情"><span>查看 agent 详情</span></a></h3>
<h4 id="get-agent-info-agent-id" tabindex="-1"><a class="header-anchor" href="#get-agent-info-agent-id"><span>GET <code v-pre>/agent/info/{agent_id}</code></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">export interface Request {</span>
<span class="line">    agent_id: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface RequestHeaders {</span>
<span class="line">    Authorization?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Response {</span>
<span class="line">    code: number;</span>
<span class="line">    data: Data;</span>
<span class="line">    msg: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Data {</span>
<span class="line">    agent_id: string;</span>
<span class="line">    agent_type: string;</span>
<span class="line">    avatar: string;</span>
<span class="line">    component_type: string;</span>
<span class="line">    created_at: string;</span>
<span class="line">    description: string;</span>
<span class="line">    model: Model;</span>
<span class="line">    name: string;</span>
<span class="line">    parameters: Parameters;</span>
<span class="line">    system_message: string;</span>
<span class="line">    updated_at: string;</span>
<span class="line">    user_id: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Model {</span>
<span class="line">    created_at: string;</span>
<span class="line">    icon_url: string;</span>
<span class="line">    model_type: string;</span>
<span class="line">    provider: string;</span>
<span class="line">    system_model_id: string;</span>
<span class="line">    updated_at: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Parameters {</span>
<span class="line">    system_prompt_role: string;</span>
<span class="line">    system_prompt_task_skill: string;</span>
<span class="line">    temperature: number;</span>
<span class="line">}</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="team" tabindex="-1"><a class="header-anchor" href="#team"><span>Team</span></a></h2>
<h3 id="查看-team-列表" tabindex="-1"><a class="header-anchor" href="#查看-team-列表"><span>查看 team 列表</span></a></h3>
<h4 id="get-team-lists" tabindex="-1"><a class="header-anchor" href="#get-team-lists"><span>GET <code v-pre>/team/lists</code></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">export interface Request {</span>
<span class="line">    page_num?: number;</span>
<span class="line">    page_size?: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface RequestHeaders {</span>
<span class="line">    Authorization?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Response {</span>
<span class="line">    code: number;</span>
<span class="line">    data: Data;</span>
<span class="line">    msg: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Data {</span>
<span class="line">    data: Datum[];</span>
<span class="line">    page_num: number;</span>
<span class="line">    page_size: number;</span>
<span class="line">    total: number;</span>
<span class="line">    total_page: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Datum {</span>
<span class="line">    agents: Agent[];</span>
<span class="line">    component_type: string;</span>
<span class="line">    created_at: string;</span>
<span class="line">    description: string;</span>
<span class="line">    model: Model;</span>
<span class="line">    name: string;</span>
<span class="line">    parameters: DatumParameters;</span>
<span class="line">    team_id: string;</span>
<span class="line">    team_type: string;</span>
<span class="line">    termination: string;</span>
<span class="line">    updated_at: string;</span>
<span class="line">    user_id: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Agent {</span>
<span class="line">    agent_id: string;</span>
<span class="line">    agent_type: string;</span>
<span class="line">    component_type: string;</span>
<span class="line">    created_at: string;</span>
<span class="line">    description: string;</span>
<span class="line">    name: string;</span>
<span class="line">    parameters: AgentParameters;</span>
<span class="line">    system_message: string;</span>
<span class="line">    updated_at: string;</span>
<span class="line">    user_id: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface AgentParameters {</span>
<span class="line">    system_prompt_role: string;</span>
<span class="line">    system_prompt_task_skill: string;</span>
<span class="line">    temperature: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Model {</span>
<span class="line">    api_key: string;</span>
<span class="line">    base_url: string;</span>
<span class="line">    created_at: string;</span>
<span class="line">    icon_url: string;</span>
<span class="line">    model_type: string;</span>
<span class="line">    provider: string;</span>
<span class="line">    system_model_id: string;</span>
<span class="line">    updated_at: string;</span>
<span class="line">    user_id: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface DatumParameters {</span>
<span class="line">    max_turns: number;</span>
<span class="line">    system_prompt_role: string;</span>
<span class="line">    system_prompt_task_skill: string;</span>
<span class="line">    temperature: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查看-team-详情" tabindex="-1"><a class="header-anchor" href="#查看-team-详情"><span>查看 team 详情</span></a></h3>
<h4 id="get-team-info-team-id" tabindex="-1"><a class="header-anchor" href="#get-team-info-team-id"><span>GET <code v-pre>/team/info/{team_id}</code></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">export interface Request {</span>
<span class="line">    team_id: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface RequestHeaders {</span>
<span class="line">    Authorization?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Response {</span>
<span class="line">    code: number;</span>
<span class="line">    data: Data;</span>
<span class="line">    msg: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Data {</span>
<span class="line">    agents: Agent[];</span>
<span class="line">    component_type: string;</span>
<span class="line">    created_at: string;</span>
<span class="line">    description: string;</span>
<span class="line">    model: Model;</span>
<span class="line">    name: string;</span>
<span class="line">    parameters: DataParameters;</span>
<span class="line">    team_id: string;</span>
<span class="line">    team_type: string;</span>
<span class="line">    termination: string;</span>
<span class="line">    updated_at: string;</span>
<span class="line">    user_id: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Agent {</span>
<span class="line">    agent_id?: string;</span>
<span class="line">    agent_type?: string;</span>
<span class="line">    component_type?: string;</span>
<span class="line">    created_at?: string;</span>
<span class="line">    description?: string;</span>
<span class="line">    name?: string;</span>
<span class="line">    parameters?: AgentParameters;</span>
<span class="line">    system_message?: string;</span>
<span class="line">    updated_at?: string;</span>
<span class="line">    user_id?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface AgentParameters {</span>
<span class="line">    system_prompt_role: string;</span>
<span class="line">    system_prompt_task_skill: string;</span>
<span class="line">    temperature: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Model {</span>
<span class="line">    api_key: string;</span>
<span class="line">    base_url: string;</span>
<span class="line">    created_at: string;</span>
<span class="line">    icon_url: string;</span>
<span class="line">    model_type: string;</span>
<span class="line">    provider: string;</span>
<span class="line">    system_model_id: string;</span>
<span class="line">    updated_at: string;</span>
<span class="line">    user_id: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface DataParameters {</span>
<span class="line">    max_turns: number;</span>
<span class="line">    system_prompt_role: string;</span>
<span class="line">    system_prompt_task_skill: string;</span>
<span class="line">    temperature: number;</span>
<span class="line">}</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="api-key" tabindex="-1"><a class="header-anchor" href="#api-key"><span>API Key</span></a></h2>
<h3 id="api-key-创建" tabindex="-1"><a class="header-anchor" href="#api-key-创建"><span>Api Key 创建</span></a></h3>
<h4 id="post-user-apikey-new" tabindex="-1"><a class="header-anchor" href="#post-user-apikey-new"><span>POST <code v-pre>/user/apikey/new</code></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">export interface RequestHeaders {</span>
<span class="line">    Authorization?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface RequestBody {</span>
<span class="line">    name: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Response {</span>
<span class="line">    code: number;</span>
<span class="line">    data: Data;</span>
<span class="line">    msg: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Data {</span>
<span class="line">    api_key: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="api-key-删除" tabindex="-1"><a class="header-anchor" href="#api-key-删除"><span>Api Key 删除</span></a></h3>
<h4 id="delete-user-apikey-delete-id" tabindex="-1"><a class="header-anchor" href="#delete-user-apikey-delete-id"><span>DELETE <code v-pre>/user/apikey/delete/{id}</code></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">export interface Request {</span>
<span class="line">    id: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface RequestHeaders {</span>
<span class="line">    Authorization?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Response {</span>
<span class="line">    code: number;</span>
<span class="line">    data: { [key: string]: any };</span>
<span class="line">    msg: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="api-key-列表" tabindex="-1"><a class="header-anchor" href="#api-key-列表"><span>Api Key 列表</span></a></h3>
<h4 id="get-user-apikey-lists" tabindex="-1"><a class="header-anchor" href="#get-user-apikey-lists"><span>GET <code v-pre>/user/apikey/lists</code></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">export interface Request {</span>
<span class="line">    page_num?: number;</span>
<span class="line">    page_size?: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface RequestHeaders {</span>
<span class="line">    Authorization?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Response {</span>
<span class="line">    code: number;</span>
<span class="line">    data: Data;</span>
<span class="line">    msg: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Data {</span>
<span class="line">    data: Datum[];</span>
<span class="line">    page_num: number;</span>
<span class="line">    page_size: number;</span>
<span class="line">    total: number;</span>
<span class="line">    total_page: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Datum {</span>
<span class="line">    api_key: string;</span>
<span class="line">    created_at: string;</span>
<span class="line">    id: number;</span>
<span class="line">    last_used_at: string;</span>
<span class="line">    name: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="用户-credit-消费历史" tabindex="-1"><a class="header-anchor" href="#用户-credit-消费历史"><span>用户 credit 消费历史</span></a></h3>
<h4 id="get-user-call-lists" tabindex="-1"><a class="header-anchor" href="#get-user-call-lists"><span>GET <code v-pre>/user/call/lists</code></span></a></h4>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">export interface Request {</span>
<span class="line">    api_key_name?: string;</span>
<span class="line">    end_date?: string;</span>
<span class="line">    order?: string;</span>
<span class="line">    order_field?: string;</span>
<span class="line">    page_num?: number;</span>
<span class="line">    page_size?: number;</span>
<span class="line">    platform?: string;</span>
<span class="line">    start_date?: string;</span>
<span class="line">    status?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface RequestHeaders {</span>
<span class="line">    Authorization?: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Response {</span>
<span class="line">    code: number;</span>
<span class="line">    data: Data;</span>
<span class="line">    msg: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line"></span>
<span class="line">export interface Data {</span>
<span class="line">    data: Datum[];</span>
<span class="line">    page_num: number;</span>
<span class="line">    page_size: number;</span>
<span class="line">    total: number;</span>
<span class="line">    total_page: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Datum {</span>
<span class="line">    api_key_name: string;</span>
<span class="line">    auth_captcha: Authcaptcha;</span>
<span class="line">    browser_id: string;</span>
<span class="line">    cost: Cost;</span>
<span class="line">    created_at: string;</span>
<span class="line">    duration: number;</span>
<span class="line">    ip_proxy_bandwidth: number;</span>
<span class="line">    session_id: string;</span>
<span class="line">    status: string;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Authcaptcha {</span>
<span class="line">    has_used: boolean;</span>
<span class="line">    used_count: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line">export interface Cost {</span>
<span class="line">    auto_captcha: number;</span>
<span class="line">    browser: number;</span>
<span class="line">    ip_proxy_bandwidth: number;</span>
<span class="line">    server_traffic: number;</span>
<span class="line">    token: number;</span>
<span class="line">    total_credit: number;</span>
<span class="line">}</span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


